AcademicManagement/AcademicManagement/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
]

AcademicManagement/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.urls import re_path
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
]

polls/urls.py
from django.urls import path
from polls import views
from .views import LoginView, StudentinfoView, SubjectLookUpView, SubjectChooseView, LogoutView
from .views import NewproView, FindidpwView, Schedule

from .views import NewLoginView, FindUserInfo, UserInfo, AddProfessor
from .views import StudentInfo, ScheduleInfo, GradeInfo, SubjectInfo, SubjectRequest, ChangePwStudent, InfoReqeustStudent
from django.views.decorators.csrf import csrf_exempt

app_name = 'polls'

urlpatterns = [
    path('', LoginView.as_view(), name="loginpage"),
    path('newpro/', NewproView.as_view(), name="newpro"),
    path('findidpw/', FindidpwView.as_view(), name="findidpw"),
    path('studentinfopage/', StudentinfoView.as_view(), name="studentInfo"),
    path('schedule/', Schedule.as_view(), name="schedule"),
    path('subjectlookup/', SubjectLookUpView.as_view(), name="subjectLookUp"),
    path('choose/', SubjectChooseView.as_view(), name="subjectChoose"),
    path('logout/', LogoutView.as_view(), name="logout"),

    path('login/', NewLoginView.as_view(), name="login"),
    path('finduserinfo/', FindUserInfo.as_view(), name="finduserinfo"),
    path('userinfo/', UserInfo.as_view(), name="userinfo"),
    path('addprofessor/', AddProfessor.as_view(), name="addprofessor"),

    path('studentinfo/', StudentInfo.as_view(), name="studentinfo"),
    path('scheduleinfo/', ScheduleInfo.as_view(), name="scheduleinfo"),
    path('gradeinfo/', GradeInfo.as_view(), name="gradeinfo"),
    path('subjectinfo/', SubjectInfo.as_view(), name="subjectinfo"),
    path('subjectrequest/', SubjectRequest.as_view(), name="subjectrequest"),
    path('changepw_s/', ChangePwStudent.as_view(), name="changepw_s"),
    path('inforequest_s/', InfoReqeustStudent.as_view(), name="inforequest_s"),
]

polls/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import View, TemplateView

from polls.models import Logintbl, Studentinfotbl
from polls.models import Fixmajorsubjecttbl, Fixculturesubjecttbl
from polls.models import Majorsubjecttbl, Culturesubjecttbl
from polls.models import Departmenttbl
from polls.models import Subjectgroup1Tbl, Subjectgroup2Tbl
from polls.models import Basket1Tbl, Basket2Tbl
from polls.models import Score1Tbl, Score2Tbl
import json


class LoginView(View):
    template_name = 'polls/loginpage.html'

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)

    def post(self, request, *args, **kwargs):
        username = request.POST.get('userSanbun', None)
        userpw = request.POST.get('passwd', None)

        alluser = Logintbl.objects.all()
        flag = False

        if not (username and userpw):
            return HttpResponseRedirect(reverse('polls:loginpage'))
        else:
            for userid in alluser:
                if userid.id == username:
                    loginuser = userid
                    flag = True
                    break

            if not flag:
                return HttpResponseRedirect(reverse('polls:loginpage'))

            if loginuser.password == userpw:
                request.session['user'] = loginuser.id
                return redirect('studentInfo/')
            else:
                return HttpResponseRedirect(reverse('polls:loginpage'))

        return render(request, self.template_name)


class NewproView(TemplateView):
    template_name = 'polls/newPro.html'


class FindidpwView(TemplateView):
    template_name = 'polls/findIdPw.html'


class StudentinfoView(View):
    template_name = 'polls/studentInformation.html'

    def get(self, request, *args, **kwargs):
        user = request.session['user']
        students = Studentinfotbl.objects.get(student=user)
        return render(request, self.template_name, {'students': students})


class Schedule(View):
    template_name = 'polls/schedule.html'

    def get(self, request, *args, **kwargs):
        loginuser = request.session['user']

        context = {'loginuser': loginuser}

        return render(request, self.template_name, context=context)


@method_decorator(csrf_exempt, name='dispatch')
class SubjectLookUpView(View):
    template_name = 'polls/subjectLookUp.html'

    def get(self, request, *args, **kwargs):
        loginuser = request.session['user']
        user = get_object_or_404(Logintbl, pk=loginuser)
        fixmajorsubjects = Fixmajorsubjecttbl.objects.all()
        fixculturesubjects = Fixculturesubjecttbl.objects.all()
        majorsubjects = Majorsubjecttbl.objects.all()
        culturesubjects = Culturesubjecttbl.objects.all()
        department = Departmenttbl.objects.all()
        context = {'user': user, 'fixmajorsubjects': fixmajorsubjects, 'fixculturesubjects': fixculturesubjects,
                   'majorsubjects': majorsubjects, 'culturesubjects': culturesubjects, 'department': department}

        return render(request, self.template_name, context=context)

    def post(self, request, *args, **kwargs):
        userdata = json.loads(request.body)

        loginuser = request.session['user']
        user = get_object_or_404(Logintbl, pk=loginuser)

        if loginuser == '2015032094':
            if Basket1Tbl.objects.count() < 8:
                try:
                    Basket1Tbl.objects.get(subject=userdata[2])
                except:
                    basketdata = Basket1Tbl()
                    basketdata.department = userdata[1]
                    basketdata.subject = userdata[2]
                    basketdata.score = userdata[3]
                    basketdata.professor = userdata[4]
                    basketdata.time = userdata[5]
                    basketdata.place = userdata[6]
                    basketdata.nowmember = userdata[7]
                    basketdata.total = userdata[8]
                    basketdata.save()
        elif loginuser == '20032094':
            if Basket2Tbl.objects.count() < 8:
                try:
                    Basket2Tbl.objects.get(subject=userdata[2])
                except:
                    basketdata = Basket2Tbl()
                    basketdata.department = userdata[1]
                    basketdata.subject = userdata[2]
                    basketdata.score = userdata[3]
                    basketdata.professor = userdata[4]
                    basketdata.time = userdata[5]
                    basketdata.place = userdata[6]
                    basketdata.nowmember = userdata[7]
                    basketdata.total = userdata[8]
                    basketdata.save()

        fixmajorsubjects = Fixmajorsubjecttbl.objects.all()
        fixculturesubjects = Fixculturesubjecttbl.objects.all()
        majorsubjects = Majorsubjecttbl.objects.all()
        culturesubjects = Culturesubjecttbl.objects.all()
        department = Departmenttbl.objects.all()

        context = {'user': user, 'fixmajorsubjects': fixmajorsubjects, 'fixculturesubjects': fixculturesubjects,
                   'majorsubjects': majorsubjects, 'culturesubjects': culturesubjects, 'department': department}

        return render(request, self.template_name, context=context)


@method_decorator(csrf_exempt, name='dispatch')
class SubjectChooseView(View):
    template_name = 'polls/subjectChoose.html'

    def get(self, request, *args, **kwargs):
        loginuser = request.session['user']
        user = get_object_or_404(Logintbl, pk=loginuser)

        if loginuser == '2015032094':
            basketsubjects = Basket1Tbl.objects.all()
        elif loginuser == '20032094':
            basketsubjects = Basket2Tbl.objects.all()

        context = {'user': user, 'basketsubjects': basketsubjects}

        return render(request, self.template_name, context=context)

    def post(self, request, *args, **kwargs):
        subjectdata = json.loads(request.body)

        loginuser = request.session['user']
        user = get_object_or_404(Logintbl, pk=loginuser)

        students = Studentinfotbl.objects.get(student=loginuser)

        if loginuser == '2015032094':
            basketsubjects = Basket1Tbl.objects.all()
        elif loginuser == '20032094':
            basketsubjects = Basket2Tbl.objects.all()

        if subjectdata[0] == "-1":
            pass
        elif subjectdata[0] != "":
            if loginuser == '2015032094':
                for subject_name in subjectdata:
                    basketsubject = Basket1Tbl.objects.get(subject=subject_name)
                    basketsubject.delete()
            elif loginuser == '20032094':
                print(subjectdata)
                for subject_name in subjectdata:
                    basketsubject = Basket2Tbl.objects.get(subject=subject_name)
                    basketsubject.delete()
        else:
            try:
                if subjectdata[1] == "":
                    if loginuser == '2015032094':
                        try:
                            Score1Tbl.objects.get(subjectname=subjectdata[3])
                        except:
                            scores = Score1Tbl()
                            scores.yearsemester = "0" + str(students.grade) + "01"
                            if subjectdata[3] == '컴퓨터활용':
                                scores.subjectcode = "10003"
                            elif subjectdata[3] == 'C언어의 기초':
                                scores.subjectcode = '00101'
                            scores.subjectname = subjectdata[3]
                            scores.rating = ""
                            scores.numrating = 0
                            scores.save()

                            if subjectdata[2] == '교양':
                                if subjectdata[3] == '컴퓨터활용':
                                    select_subject = Culturesubjecttbl.objects.get(culturesubjectcode='10003')
                                    select_subject.nowmember += 1
                                    select_subject.save()

                                    basket_subject = Basket1Tbl.objects.get(subject=subjectdata[3])
                                    basket_subject.nowmember += 1
                                    basket_subject.save()
                                    basket_subject2 = Basket2Tbl.objects.get(subject=subjectdata[3])
                                    basket_subject2.nowmember += 1
                                    basket_subject2.save()
                                else:
                                    pass
                            else:
                                if subjectdata[3] == 'C언어의 기초':
                                    select_subject = Majorsubjecttbl.objects.get(majorsubjectcode='00101')
                                    select_subject.nowmember += 1
                                    select_subject.save()

                                    basket_subject = Basket1Tbl.objects.get(subject=subjectdata[3])
                                    basket_subject.nowmember += 1
                                    basket_subject.save()
                                    basket_subject2 = Basket2Tbl.objects.get(subject=subjectdata[3])
                                    basket_subject2.nowmember += 1
                                    basket_subject2.save()
                                else:
                                    pass
                    elif loginuser == '20032094':
                        try:
                            Score2Tbl.objects.get(subjectname=subjectdata[3])
                        except:
                            scores = Score2Tbl()

polls/templates/polls/findIdPw.html
<!DOCTYPE html>
<html>
<head>
  {% load static %}
  <script src="{% static '/javascript/jquery-3.5.1.min.js' %}"></script>
  <script src="{% static '/javascript/checkAddr.js' %}"></script>
</head>
<body>
  <div id="findIdResult">
    <p><strong>[아이디 찾기]</strong></p>
    <form name="findId" method="get">
      <div>
        주민등록번호 입력 <input type="text" name="frmBirthMD" size="16" placeholder="주민등록번호 앞자리">
        -
        <input type="password" name="frmSocialNum" size="16" placeholder="주민등록번호 뒷자리">
        <input type="button" value="아이디 검색" onclick="findAddrId()" role="button">
      </div>
    </form>
    <br>
    <p><strong>[비밀번호 찾기]</strong></p>
    <form name="findPw" method="get">
      <div>
        아이디 입력 <input type="text" name="frmId" placeholder="Id를 입력하세요">
      </div>
      <div>
        주민등록번호 입력 <input type="text" name="frmBirthMD" size="16" placeholder="주민등록번호 앞자리">
        -
        <input type="password" name="frmSocialNum" size="16" placeholder="주민등록번호 뒷자리">
        <input type="button" value="비밀번호 검색" onclick="findAddrPw()" role="button">
      </div>
    </form>
  </div>
</body>
</html>

polls/templates/polls/schedule.html
<!DOCTYPE html>
<html>
<head>
    {% load static %}
    <script src="{% static '/javascript/jquery-3.5.1.min.js' %}"></script>
    <style>
        table, th, td {
            border: 1px solid black;
            border-collapse: collapse;
            text-align: center;
            width : 100px;
            height: 30px;
        }
        th, td {
            padding: 20px;
        }
        th {
            text-align: center;
        }
    </style>
</head>
<body>
    {% load static %}
    <div id="container" style="width:1500px">
      <div id="menu" style="background-color:#EEEEEE;
      height:730px;width:200px;float:left;">
        <center>
          <img src="{% static '/image/school.jpg' %}" width="95%">
        </center>
        <ul>
          <li><a href="{% url 'polls:studentInfo' %}">[학적사항]</a></li>
          <li><a href="{% url 'polls:schedule' %}">[수강과목/시간표]</a></li>
          <li><a href="{% url 'polls:subjectLookUp' %}">[과목 조회]</a></li>
          <li><a href="{% url 'polls:subjectChoose' %}">[수강신청]</a></li>
          <li>[성적조회]</li>
          <hr>
          <li><a href="changePw.html">[로그인 암호변경]</a></li>
          <hr>
          <li><a href="{% url 'polls:logout' %}">[로그아웃]</a></li>
        </ul>
      </div>

      {% if loginuser == '2015032094' %}
          <table style="width:1200px;height:730px;float:right;">

            <tr>
                <th> </th>
                <th>월</th>
                <th>화</th>
                <th>수</th>
                <th>목</th>
                <th>금</th>
            </tr>
            <tr>
                <th>09:00~10:00</th>
                <td style = "background : Plum  ;"rowspan="2">컴퓨터활용</td>
                <td> </td>
                <td style = "background : LavenderBlush ;"rowspan="2">정보통신융합공학개론</td>
                <td> </td>
                <td style = "background : LightGoldenRodYellow;" rowspan="2">C언어의 기초</td>
            </tr>
            <tr>
                <th>10:00~11:00</th>
                <td> </td>
                <td> </td>
            </tr>
            <tr>
                <th>11:00~12:00</th>
                <td> </td>
                <td> </td>
                <td style = "background : LightCyan  ;" rowspan="2">프로그래밍언어구조론</td>
                <td> </td>
                <td> </td>
            </tr>
            <tr>
                <th>12:00~13:00</th>
                <td> </td>
                <td> </td>
                <td> </td>
                <td> </td>
            </tr>
            <tr>
                <th>13:00~14:00</th>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <th>14:00~15:00</th>
                <td></td>
                <td style = "background : Salmon  ;" rowspan="4">c++ </td>
                <td style = "background : MintCream  ;" rowspan="4">임베디드프로그래밍실습</td>
                <td style = "background : Pink ;" rowspan="2">화일구조</td>
                <td style = "background : Wheat   ;" rowspan="4">리눅스컴퓨팅실무</td>
            </tr>
            <tr>
                <th>15:00~16:00</th>
                <td style = "background : Lavender  ;" rowspan="2">웹/xml프로그래밍</td>
            </tr>
            <tr>
               <th>16:00~17:00</th>
               <td style = "background : Lavender;" rowspan="2">웹/xml프로그래밍</td>
            </tr>
            <tr>
               <th>17:00~18:00</th>
               <td style = "background : LightCyan  ;">프로그래밍언어구조론</td>
            </tr>
          </table>
      {% elif loginuser == '20032094' %}
          <table style="width:1200px;height:730px;float:right;">

            <tr>
                <th> </th>
                <th>월</th>
                <th>화</th>
                <th>수</th>
                <th>목</th>
                <th>금</th>
            </tr>
            <tr>
                <th>09:00~10:00</th>
                <td style = "background : Plum  ;">컴퓨터활용</td>
                <td> </td>
                <td style = "background : LavenderBlush ;"rowspan="2">정보통신융합공학개론</td>
                <td style = "background : Pink ;" rowspan="2">화일구조</td>
                <td style = "background : LightGoldenRodYellow;" rowspan="2">C언어의 기초</td>
            </tr>
            <tr>
                <th>10:00~11:00</th>
                <td> </td>
                <td> </td>
            </tr>
            <tr>
                <th>11:00~12:00</th>
                <td> </td>
                <td> </td>
                <td style = "background : LightCyan  ;" rowspan="2">프로그래밍언어구조론</td>
                <td style = "background : Lavender;" rowspan="2">웹/xml프로그래밍</td>
                <td> </td>
            </tr>
            <tr>
                <th>12:00~13:00</th>
                <td> </td>
                <td> </td>
                <td> </td>
            </tr>
            <tr>
                <th>13:00~14:00</th>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <th>14:00~15:00</th>
                <td style = "background : Lavender  ;" rowspan="2">웹/xml프로그래밍</td>
                <td style = "background : Salmon  ;" rowspan="4">c++ </td>
                <td style = "background : MintCream  ;" rowspan="4">임베디드프로그래밍실습</td>
                <td> </td>
                <td style = "background : Wheat   ;" rowspan="4">리눅스컴퓨팅실무</td>
            </tr>
            <tr>
                <th>15:00~16:00</th>
                <td> </td>
            </tr>
            <tr>
               <th>16:00~17:00</th>
               <td> </td>
               <td> </td>
            </tr>
            <tr>
               <th>17:00~18:00</th>
               <td style = "background : LightCyan  ;">프로그래밍언어구조론</td>
               <td> </td>
            </tr>
          </table>
      {% endif %}
    </div>
</body>
</html>

polls/templates/polls/studentInformation.html
<!DOCTYPE html>
<html>
  <head>
  </head>
  <body>
    {% load static %}
    <div id="container" style="width:1500px">
      <div id="menu" style="background-color:#EEEEEE;
      height:730px;width:200px;float:left;">
        <center>
          <img src="{% static '/image/school.jpg' %}" width="95%">
        </center>
        <ul>
          <li><a href="{% url 'polls:studentInfo' %}">[학적사항]</a></li>
          <li><a href="{% url 'polls:schedule' %}">[수강과목/시간표]</a></li>
          <li><a href="{% url 'polls:subjectLookUp' %}">[과목 조회]</a></li>
          <li><a href="{% url 'polls:subjectChoose' %}">[수강신청]</a></li>
          <li>[성적조회]</li>
          <hr>
          <li><a href="changePw.html">[로그인 암호변경]</a></li>
          <hr>
          <li><a href="{% url 'polls:logout' %}">[로그아웃]</a></li>
        </ul>
      </div>
      <div id="content" style="background-color:#EEEEEE;
        height:730;width:1275px;float:right;">[학적정보조회]
        <div id="information">
          <table border="1" width="100%">
            <tr>
              <td rowspan="9" align="center" width="5%">
                학적
                <br>
                사항
              </td>
            <tr>
              <td class="title" width="8%">사진</td>
              <td><img src="{% static '/image/coding.jpg' %}" width="95" height="110"></td>
            </tr>
            <tr>
              <td class="title" width="8%">성 명</td>
              <td colspan="5" align="left">
                * 한글
                <input type="text" name="frmStudentName" size="15" value="{{students.username}}" readonly>
                * 한자
                <input type="text" name="frmHanjaName" size="15" value="" readonly>
                * 영문
                <input type="text" name="frmEngName" size ="30" value="" readonly>
              </td>
            </tr>
            <tr class="height">
              <td class="title">출신고교</td>
              <td width="35%">
                <input type="text" name="frmGogyoName" size="20" value="">
                소재지 :
                <input type="text" name="frmGogyoSojae" size="8" value="">
              </td>
              <td class="title" width="8%">
                고교
                <br>
                전공
              </td>
              <td>
                <input type="text" name="frmGogyoMajor" value="">
              </td>
              <td class="title" width="8%">
                고교
                <br>
                졸업연월
              </td>
              <td>
                <input type="text" name="frmGogyoJolup" size="10" value="">
              </td>
            </tr>
            <tr class="height">
              <td class="title">출신대학</td>
              <td>
                <input type="text" name="frmGogyoName" size="20" value="">
                소재지 :
                <input type="text" name="frmGogyoSojae" size="8" value="">
              </td>
              <td class="title">
                대학
                <br>
                전공
              </td>
              <td>
                <input type="text" name="frmColMajor" value="">
              </td>
              <td class="title">
                대학
                <br>
                졸업연월
              </td>
              <td>
                <input type="text" name="frmColJolDate" size="10" value="">
                <select name="frmColJol" id="frmCoJol" onchange>
                  <option value selected="selected"></option>
                  <option value="재학">재학</option>
                  <option value="중퇴">중퇴</option>
                  <option value="졸업">졸업</option>
                  <option value="수료">수료</option>
                </select>
              </td>
            </tr>
          </table>
        </div>
      </div>
    </div>
  </body>
</html>

polls/templates/polls/subjectChoose.html
<!DOCTYPE html>
<html>
  <head>
    {% load static %}
    <script src="{% static '/javascript/jquery-3.5.1.min.js' %}"></script>
    <script src="{% static '/javascript/logout.js' %}"></script>
    <style type="text/css">
      tr, td{
        border : 1px solid black;
      }
      #chooseSubjectTBL{
        width:775px;
        height:300px;
        margin: auto;
        display: block;
        border-collapse: collapse;
        background: white;
      }
      td{
        text-align: center;
      }
      th{
        border : 2px solid black;
        background-color : #00BFFF;
      }
    </style>
  </head>
  <body>
    {% load static %}
    <div style="height:730px; width:1475px;">
      <div id="menu" style="background-color:#EEEEEE;
      height:730px;width:200px;float:left;">
        <center>
          <img src="{% static '/image/school.jpg' %}" width="95%">
        </center>
        <ul>
          <li><a href="{% url 'polls:studentInfo' %}">[학적사항]</a></li>
          <li><a href="{% url 'polls:schedule' %}">[수강과목/시간표]</a></li>
          <li><a href="{% url 'polls:subjectLookUp' %}">[과목 조회]</a></li>
          <li><a href="{% url 'polls:subjectChoose' %}">[수강신청]</a></li>
          <li>[성적조회]</li>
          <hr>
          <li><a href="changePw.html">[로그인 암호변경]</a></li>
          <hr>
          <li><a href="{% url 'polls:logout' %}">[로그아웃]</a></li>
        </ul>
      </div>
      <center>
        <script type="text/javascript" charset="utf-8">
        var cnum = [];
        var j = 0;
        var flag = false;

        {% autoescape off %}
          {% if basketsubjects %}
            {% for csubject in basketsubjects %}
              cnum[j] = {'department':'{{csubject.department}}','subject':'{{csubject.subject}}','score':'{{csubject.score}}','professor':'{{csubject.professor}}','time':'{{csubject.time}}','place':'{{csubject.place}}','nowmember':'{{csubject.nowmember}}', 'total':'{{csubject.total}}'};
              j++;
            {% endfor %}
          {% endif %}
        {% endautoescape %}

        document.write("<table style=\"padding-top:220px;\">");
          document.write("<table id=\"chooseSubjectTBL\" style=\"overflow:auto;\">");
            document.write("<th>"+"<input type=\"checkbox\" name=\"chk_all\" id=\"chk_all\">"+"</th>");
            document.write("<th>"+"희망"+"<br>"+"과목"+"</th>");
            document.write("<th>"+"학과"+"</th>");
            document.write("<th>"+"과목명"+"</th>");
            document.write("<th>"+"학점"+"</th>");
            document.write("<th>"+"담당교수"+"</th>");
            document.write("<th>"+"강의시간"+"</th>");
            document.write("<th>"+"강의실"+"</th>");
            document.write("<th>"+"신청인원"+"</th>");
            document.write("<th>"+"총인원"+"</th>");

            for(i = 0; i < cnum.length; i++)
            {
               document.write("<tr>");
               document.write("<td style=\"width:50px\">"+"<input type=\"checkbox\" name=\"chk_subject\" class=\"chk_subject\" value=\"\">"+"</td>");
               document.getElementsByClassName("chk_subject")[i].value = cnum[i].subject;
               document.write("<td style=\"width:100px\">"+"<input type=\"button\" class=\"select_subject\" value=\"수강신청\" />"+"</td>");
               document.write("<td style=\"width:120px\">"+cnum[i].department+"</td>");
               document.write("<td style=\"width:120px\">"+cnum[i].subject+"</td>");
               document.write("<td style=\"width:40px\">"+cnum[i].score+"</td>");
               document.write("<td style=\"width:80px\">"+cnum[i].professor+"</td>");
               document.write("<td style=\"width:150px\">"+cnum[i].time+"</td>");
               document.write("<td style=\"width:70px\">"+cnum[i].place+"</td>");
               document.write("<td style=\"width:70px\">"+cnum[i].nowmember+"</td>");
               document.write("<td style=\"width:50px\">"+cnum[i].total+"</td>");
              document.write("</tr>");
            }

          document.write("</table>");
        document.write("</table>");


          $(document).off("click").on("click", ".select_subject", function(){
            if(!flag){
              alert("수강 신청이 완료되었습니다.");

              var subjectArr = new Array();
              var tr = $(this).parent().parent();
              var td = tr.children();

              td.each(function(i){
              subjectArr.push(td.eq(i).text());
              });

              var jsonString = JSON.stringify(subjectArr);
              $.ajax({
                type : "POST",
                url : 'http://127.0.0.1:8000/polls/choose/',
                data : jsonString,
                dataType : 'json',
                error : function(xhr, status, error){
              }
             });
            }
            else{
              alert("수강 신청이 실패되었습니다. (중복신청)");

              var subjectArr = new Array();
              subjectArr.push("");
              subjectArr.push("1");
              var jsonString = JSON.stringify(subjectArr);
              $.ajax({
                type : "POST",
                url : 'http://127.0.0.1:8000/polls/choose/',
                data : jsonString,
                dataType : 'json',
                error : function(xhr, status, error){
              }
             });
            }
          })

          $("#chk_all").on('change',function(){
            if($("#chk_all").prop("checked")){
              $(".chk_subject").prop("checked", true)
            }
            else{
              $(".chk_subject").prop("checked", false)
            }
          })

        </script>
      </center>
      <div>
        <input type="button" id="delete" value="과목 삭제" style="margin-left : 950px">
      </div>
      <script type="text/javascript" charset="utf-8">

        $("#delete").on('click',function(){
          var chk_arr = new Array();


              for ( var i = 0; i < $("input[name=chk_subject]:checkbox" ).length; i++){
                if ($( "input[name=chk_subject]:checkbox")[i].checked == true ){
                  chk_arr.push($( "input[name=chk_subject]:checkbox")[i].value);
                }
              }

              if(chk_arr.length == 0){
                chk_arr.push("-1");
              }

              var jsonString = JSON.stringify(chk_arr);
              $.ajax({
                type : "POST",
                url : 'http://127.0.0.1:8000/polls/choose/',
                data : jsonString,
                dataType : 'json',
                error : function(xhr, status, error){
              }
             });

        })
      </script>
    </div>
  </body>
</html>